'use strict';

module.exports = {
  BUY_SIDE: 1,
  SELL_SIDE: 0,
  BTC_USD_INDEX: 0,
  BTC_USD_SYMBOL: 'BTC/USD',
  ETH_USD_INDEX: 1,
  ETH_USD_SYMBOL: 'ETH/USD',
  USDT_COLLATERAL_INDEX: 0,
  BTC_COLLATERAL_INDEX: 1,
  INT_PRECISION_EVEDEX: 10n ** 8n,
  INT_PRECISION_DEPOSIT_DEX: 10n ** 8n,
  USDT_DECIMALS: 6n,
  BTC_DECIMALS: 8n,
};
